[workspace]
resolver = "2"
members = [
    "examples",
    "twilight-interactions",
    "twilight-interactions-derive",
]

[patch.crates-io]
twilight-model = { git = "https://github.com/twilight-rs/twilight.git", rev = "7e864ec39059fa1194dc36341b5befbfff8250c1" }

